# {{PROJECT_NAME}}

<!-- ไฟล์นี้เป็นภาษาอังกฤษโดยตั้งใจ: AI อ่านทุก session และภาษาไทย tokenize แพงกว่า ~2 เท่า
     คำตอบต่อผู้ใช้และไฟล์ใน docs/ ยังเป็นภาษาไทยตามกติกา (ดูหมวด Language) -->

> Core rules for **every AI agent** working in this repo (AGENTS.md standard).
> Claude Code loads this through `CLAUDE.md`, which imports it.
> **Keep under ~200 lines.** Details live in `docs/` — link, don't paste.
> Test for every line: *"If this line were deleted, would the AI get something wrong?"* If not, delete it.

## Language

- **Reply to the user in Thai.** Technical terms, identifiers, file names, branch names, commit messages, code, and i18n keys stay in English.
- **Everything written into `docs/` (intent, spec, plan, ADR, task, release note, incident) is written in full Thai** — those files are read by humans and by other sessions. Terse/compressed style applies to chat replies only.
- This file, `.claude/rules/`, `.claude/skills/`, `.claude/agents/`, and `REVIEW.md` are in English because only the AI reads them.

## What this project is
{{One paragraph: what the app is, for whom, what problem it solves}}

## Stack
- Frontend: {{...}}
- Backend: {{...}}
- DB/ORM: {{PostgreSQL + Prisma}}
- UI: {{per constitution art. 9 — React default: shadcn/ui + Radix + Tailwind}} (adding another library requires an intent + ADR)
- i18n: {{next-intl}} — **th (default) + en**
- Test: {{Vitest + Testing Library + Playwright}}
- Docker for dev and deploy

## Commands

```bash
{{VERIFY_COMMAND}}       # the standard check; must pass before claiming done (prints a short summary; full log in .verify.log)
node .claude/gate.js     # the gate before main = verify + check-config + docs-lint (pre-push and CI run this same script)
node .claude/board.js    # regenerates docs/backlog/board.md from task files — never edit board.md by hand
pnpm dev                 # dev server
pnpm build               # build
pnpm test:cov            # tests + coverage
pnpm db:migrate          # run migrations
pnpm db:seed             # seed data
pnpm docker:dev          # bring up docker compose
pnpm sonar               # the user runs this — AI must not
```

**What "passing" looks like** (anything else means not passing):

```
{{Paste the real output from a fully green run, e.g.
verify  ✓ typecheck 4.1s   ✓ lint 2.3s   ✓ test 6.8s   [13.2s]
        Tests  84 passed (84)
        all passed}}
```

**Paste only these lines** when reporting — never the full log (it is in `.verify.log` if anyone needs it).

## Folder layout

```
{{Real tree with one-line notes on what goes where}}
```

- `components/ui/` = generated by the registry — **never hand-edit** (hook enforces via `protected` in `.claude/stack.json`)
- `components/shared/` = our shared components
- `components/<feature>/` = feature-specific
- A feature must not import another feature's components — promote to `shared/` instead

---

## Workflow (always in this order)

```
intent -> spec (large feature) -> plan -> code -> verify -> check -> PR -> done
                                                 (trivial track: task -> code -> check low -> PR)
```

1. **Starting any task** — `/task` reads the board + task file, then **summarizes its understanding to the user first**. Never start coding immediately.
2. **Before touching code** — more than 3 files / DB / auth / unfamiliar code → `/plan` in plan mode, commit the plan first.
   plan.md **already distills** the ACs, the applicable constitution articles, and the design rules — during implementation and check, **read plan.md only**; do not re-read the upstream docs.
3. **While working** — one task at a time; write one step, verify one step; small Conventional Commits; anything out of scope → **stop and ask**.
   Same spot fails twice in a row → stop, tell the user; do not keep retrying in the same turn.
4. **Before claiming done** — actually run `{{VERIFY_COMMAND}}` and paste **its summary line**. Never claim "passes" without running it.
5. **Finishing** — `/check` → the user approves → `/done` opens a PR → **a human merges** after the gate passes → `/clear`.
   The AI never merges into main (hook blocks it) and never hand-edits `board.md` (generated from task files).

## Model per step (5–10× cost difference — match the model to the job)

| Step | Model | Why |
|---|---|---|
| `/intent`, `/spec` (design), `/plan`, architecture decisions | **Opus** | Thinking work — mistakes here are the most expensive |
| `/task` implementation, `/done`, hotfix with known cause | **Sonnet** | Executing an already-distilled plan |
| Search/explore subagents (`Explore`, `legacy-explorer`) | **Haiku** | Reads a lot, decides little |
| `/check` normally | Sonnet (built-in `/code-review medium`) · touches auth/money/migration → Opus + `high` | |

Switch with `/model` · long low-reasoning work can lower `/effort`

## Never

- Hardcoded UI strings — every string goes through i18n with both th and en (including placeholders, aria-labels, errors, toasts, empty states)
- Raw colors/sizes — theme tokens only
- Installing a UI library other than the one locked in constitution art. 9
- Editing test files to make tests pass while fixing a bug
- `git commit --no-verify`
- Running the SonarQube scan yourself (the user runs it and hands you the results)
- Working outside the task scope without asking
- Reporting "passes" without actually running it
- `git merge` / `git push` into main — open a PR for a human
- Hand-editing `docs/backlog/board.md` — edit the task file, then `node .claude/board.js`

## Backend

- **Write unit tests together with the module, always** — part of DoD, never deferred
- Validate every input with zod/DTO at every entry point
- Errors use the shared envelope with a `code` the frontend maps to an i18n key
- Authorize on the server, always, and check **record ownership**, not just role
- Update OpenAPI + Postman every time an API changes

## Frontend

- **Before creating a component, always ask**: exists in `shared/`? → in shadcn? → composable from existing primitives? → is there a design? → **if none, stop and ask before designing your own**
- Decide every time whether it should be shared (used in ≥ 2 places = shared) and record it in `docs/design/components.md`
- Unit tests come later once the UI is stable, but **create the `T-xxx-test` task at the time you build the UI**
- Cover every state: loading / empty / error / unauthorized
- Test th/en, light/dark, ~390px

## When the plan changes

Update the source document first (intent / spec / plan / ADR / task file), then the code.
**Never let code and docs disagree.**

## When unsure

Ask, don't guess — write `[NEEDS CLARIFICATION: <question>]` in the document instead of filling in a plausible value.
Especially for UI, business rules, and API contract changes.

---

## Things the AI gets wrong in this project

<!-- Rule: the 2nd time the same mistake happens -> add it here immediately (from review, or from a correction the user had to repeat) -->
<!-- One line per item: <what it did wrong> -> <what is correct> -->

- {{Example: put the client directive on the whole page file → put it only on the child component that needs the hook}}

> If this list grows past ~10 items, some of them should be promoted to a path-scoped rule or a hook.

## Reference docs

| Topic | File |
|---|---|
| Project constitution (non-negotiable principles) | `docs/constitution.md` |
| Workflow / releasing | `docs/workflow.md` |
| Definition of Done (core — per-type DoD lives in `.claude/rules/`) | `docs/standards/definition-of-done.md` |
| Data model (source of truth) | `prisma/schema.prisma` + `docs/planning/04-architecture.md` § 4.4b |
| Context / token budget | `docs/standards/context-budget.md` |
| Review policy | `REVIEW.md` |
| All standards | `docs/standards/` |
| Architecture / ADR | `docs/planning/04-architecture.md`, `docs/adr/` |
| Backlog | `docs/backlog/board.md` |
